[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
base_anchor = "5fdvcJ2tsUv4Ei2G49RPTA5ArV8cQ7babW85tDJX9Y2u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"
