name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install mdBook
        run: |
          mkdir -p $HOME/.cargo/bin
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-gnu.tar.gz | tar xvz -C $HOME/.cargo/bin
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build mdBook
        run: mdbook build docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/book # Default output folder for mdBook
          branch: gh-pages